#!/usr/bin/env python3
"""
generate_termbase.py
====================
Reads en-1-rhys_davids.md, computes TF-IDF against the Reuters-21578
general-English IDF corpus (idf_corpus.py), and writes rhys_davids_termbase.md
— a single ranked table of the most-distinctive and least-distinctive words
in the translation (500+ words, ranking order).

No comparison with the Pāli root text.

Usage
-----
    python3 generate_termbase.py        # from repo root or this directory
"""

import re
import sys
import pathlib
from datetime import date

# Ensure the scripts/ directory is on the path so idf_corpus is importable
# regardless of where the script is invoked from.
sys.path.insert(0, str(pathlib.Path(__file__).parent))
from idf_corpus import IDF_CORPUS

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
HERE      = pathlib.Path(__file__).parent
REPO_ROOT = HERE.parent                             # abhidhamma-rails/
EN_SOURCE = REPO_ROOT / "1-SOURCES/Translations/en-1-rhys_davids.md"
OUTPUT    = HERE / "output/rhys_davids_termbase.md"

# ---------------------------------------------------------------------------
# IDF table  — Reuters-21578 corpus (10,788 newswire documents)
#
# Sourced from idf_corpus.py (generated by generate_idf_corpus.py).
# Formula: idf(t) = log((1 + N) / (1 + df(t))) + 1  [sklearn smooth IDF]
#
# Approximate scoring bands in this corpus:
#   1.0  – 1.5   function / grammatical words   (present in nearly every document)
#   1.5  – 3.0   common content words
#   3.0  – 6.0   moderately rare / domain words
#   6.0  – 9.0   uncommon / specialist English
#   9.0  – 9.6   near-hapax in Reuters (max ≈ log(10789/2)+1 ≈ 9.59)
#
# Words absent from the corpus (Pāli transliterations, Victorian coinages)
# receive IDF_UNKNOWN — set to the corpus maximum to mark them as maximally
# rare from a general-English perspective.
# ---------------------------------------------------------------------------
IDF: dict[str, float] = IDF_CORPUS

# Fallback for words absent from the Reuters vocabulary.
# Near-maximum corpus IDF (≈ hapax legomenon in 10 788 docs).
IDF_UNKNOWN: float = 9.59

# ---------------------------------------------------------------------------
# Stop-words (excluded from counting — grammatical skeleton only)
# ---------------------------------------------------------------------------
STOPWORDS = {
    "the","a","an","and","or","of","in","on","to","at","by","for","with",
    "that","this","these","those","is","are","was","were","be","been","being",
    "have","has","had","do","does","did","will","would","shall","should",
    "may","might","can","could","not","no","nor","so","yet","but","both",
    "either","neither","as","if","then","there","here","when","where","which",
    "who","whom","whose","what","how","it","its","he","she","they","we","you",
    "i","me","him","her","them","us","my","your","his","our","their",
    "from","into","up","out","about","after","before","between","through",
    "now","also","only","just","even","than","more","very","each","all","any",
    "some","such","other","same","own","new","first","last","long","great",
    "little","good","well","back","over","still","though","however","thus",
    "upon","per","own","one","two","three","four","five","six","seven","eight",
}

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def strip_frontmatter(text: str) -> str:
    if text.startswith("---"):
        end = text.find("\n---", 3)
        if end != -1:
            return text[end + 4:]
    return text


def tokenize(text: str) -> list[str]:
    text = strip_frontmatter(text)
    text = re.sub(r"\^[\w\-]+", " ", text)           # verse markers
    text = re.sub(r"[#\[\]`*_>|§]", " ", text)       # markdown syntax
    text = re.sub(r"\d+", " ", text)                  # numbers
    # keep hyphened compounds as single tokens (e.g. self-collectedness)
    tokens = re.findall(
        r"[a-zA-ZāīūṭḍṅñṇḷṃṁĀĪŪṬḌṄÑṆḶṂṀ]+"
        r"(?:[-][a-zA-ZāīūṭḍṅñṇḷṃṁĀĪŪṬḌṄÑṆḶṂṀ]+)*",
        text,
    )
    return [t.lower() for t in tokens]


def count_tf(path: pathlib.Path) -> dict[str, int]:
    raw    = tokenize(path.read_text(encoding="utf-8"))
    counts: dict[str, int] = {}
    for w in raw:
        if w not in STOPWORDS and len(w) > 2:
            counts[w] = counts.get(w, 0) + 1
    return counts


def tfidf(word: str, count: int, total: int) -> float:
    tf  = count / total
    idf = IDF.get(word, IDF_UNKNOWN)
    return round(tf * idf * 1_000_000, 4)


# ---------------------------------------------------------------------------
# Build rows sorted by TF-IDF descending
# ---------------------------------------------------------------------------

def build_rows(tf: dict[str, int]) -> list[dict]:
    total = sum(tf.values())
    rows  = []
    for word, count in tf.items():
        score = tfidf(word, count, total)
        rows.append({"word": word, "count": count, "score": score,
                     "idf": IDF.get(word, IDF_UNKNOWN)})
    rows.sort(key=lambda r: r["score"], reverse=True)
    return rows


# ---------------------------------------------------------------------------
# Determine TF-IDF band label
# ---------------------------------------------------------------------------
_BANDS = [
    (50_000, "🔴 extremely high — text-exclusive"),
    (10_000, "🟠 very high — domain-specific"),
    ( 3_000, "🟡 high — specialist register"),
    (   500, "🟢 medium — moderately distinctive"),
    (    50, "🔵 low — common in general English"),
    (     0, "⚪ very low — function / universal word"),
]

def band(score: float) -> str:
    for threshold, label in _BANDS:
        if score >= threshold:
            return label
    return "⚪ very low"


# ---------------------------------------------------------------------------
# Markdown renderer
# ---------------------------------------------------------------------------

def render_md(rows: list[dict]) -> str:
    today   = date.today().isoformat()
    total_w = sum(r["count"] for r in rows)
    n       = len(rows)

    # ── counts per band ──────────────────────────────────────────────────────
    band_counts: dict[str, int] = {}
    for r in rows:
        b = band(r["score"])
        band_counts[b] = band_counts.get(b, 0) + 1

    # ── top / bottom 50 for the narrative sections ───────────────────────────
    top    = rows[:50]
    bottom = rows[-50:]

    L: list[str] = []

    # frontmatter
    L += [
        "---",
        "title: TF-IDF Vocabulary Analysis — Rhys Davids Dhammasaṅgaṇī (1900)",
        "source: 1-SOURCES/Translations/en-1-rhys_davids.md",
        "corpus: Reuters-21578 (10,788 newswire documents) via NLTK · sklearn TfidfVectorizer(smooth_idf=True)",
        "method: TF × IDF — term frequency in translation vs. inverse document frequency in Reuters corpus",
        f"generated: {today}",
        f"unique_terms: {n}",
        f"total_content_tokens: {total_w:,}",
        "status: draft",
        "---",
        "",
    ]

    # title + intro
    L += [
        "# TF-IDF Vocabulary Analysis — Rhys Davids Translation",
        "",
        f"Generated **{today}** · source: `en-1-rhys_davids.md` · **{n:,} unique content terms** ranked.",
        "",
        "This report answers two questions:",
        "",
        "1. **Which words in this translation are most frequent here but rare in everyday English?**  ",
        "   → High TF-IDF score. These are the lexical signatures of the text.",
        "2. **Which words appear in the text but are also very common in general English?**  ",
        "   → Low TF-IDF score. These look familiar but carry specialist meaning here.",
        "",
        "---",
        "",
    ]

    # methodology
    L += [
        "## Methodology",
        "",
        "**Term Frequency (TF)** — count of each word in the translation, normalised by total content-token count.",
        "Frontmatter, verse markers (`^1-2`), numbers and markdown syntax are stripped before counting.",
        "",
        "**Inverse Document Frequency (IDF)** — computed from the Reuters-21578 newswire corpus",
        "(10,788 documents, ~1.3 M tokens) using sklearn's smooth IDF formula:",
        "`idf(t) = log((1 + N) / (1 + df(t))) + 1`. Corpus maximum ≈ 9.59. Scale:",
        "",
        "| IDF range | Meaning |",
        "|-----------|---------|",
        "| 1.0 – 1.5 | Function word — present in virtually every document |",
        "| 1.5 – 3.0 | Common content word — high general-English frequency |",
        "| 3.0 – 6.0 | Moderately rare — limited domain or register |",
        "| 6.0 – 9.0 | Uncommon / archaic — rare in Reuters |",
        "| 9.59 (max) | Absent from Reuters — domain-exclusive, coined, or Pāli |",
        "",
        "**TF-IDF score** = TF × IDF × 10⁶ (scaled for readability).",
        "",
        "**Colour bands** used in the table:",
        "",
        "| Band | Score range | Interpretation |",
        "|------|-------------|----------------|",
        "| 🔴 | ≥ 50,000 | Text-exclusive — word essentially does not exist outside this translation |",
        "| 🟠 | 10,000 – 49,999 | Domain-specific — Buddhist / Abhidhamma vocabulary |",
        "| 🟡 | 3,000 – 9,999 | Specialist register — unusual in general English |",
        "| 🟢 | 500 – 2,999 | Moderately distinctive — identifiable domain presence |",
        "| 🔵 | 50 – 499 | Moderately common — has general English presence |",
        "| ⚪ | 0 – 49 | Universal / function word |",
        "",
        "---",
        "",
    ]

    # band distribution
    L += [
        "## Distribution by Band",
        "",
        "| Band | Terms | % of vocabulary |",
        "|------|-------|----------------|",
    ]
    for threshold, label in _BANDS:
        c = band_counts.get(label, 0)
        pct = f"{100 * c / n:.1f}" if n else "0.0"
        L.append(f"| {label} | {c:,} | {pct}% |")
    L += ["", "---", ""]

    # top 50 narrative
    L += [
        "## Most Distinctive Words (highest TF-IDF)",
        "",
        "Words that appear **frequently in this text** yet are **rare or absent in general English**.",
        "These are the genuine lexical fingerprints of the Rhys Davids translation.",
        "",
    ]
    for i, r in enumerate(top, 1):
        b = band(r["score"])
        L.append(f"**{i}. {r['word']}** — count: {r['count']}, TF-IDF: {r['score']:,.0f}, IDF: {r['idf']} {b}")
    L += ["", "---", ""]

    # bottom 50 narrative
    L += [
        "## Least Distinctive Words (lowest TF-IDF)",
        "",
        "Words that appear in this text but are also extremely common in general English,",
        "giving them a near-zero TF-IDF score despite sometimes occurring hundreds of times here.",
        "",
    ]
    for i, r in enumerate(reversed(bottom), 1):
        b = band(r["score"])
        L.append(f"**{i}. {r['word']}** — count: {r['count']}, TF-IDF: {r['score']:,.2f}, IDF: {r['idf']} {b}")
    L += ["", "---", ""]

    # full ranked table
    L += [
        "## Full Ranked Table",
        "",
        f"All {n:,} content terms, sorted by TF-IDF descending.",
        "",
        "| Rank | Word | Count | TF-IDF | IDF | Band |",
        "|------|------|-------|--------|-----|------|",
    ]
    for i, r in enumerate(rows, 1):
        b     = band(r["score"])
        score = f"{r['score']:,.2f}"
        L.append(f"| {i} | **{r['word']}** | {r['count']} | {score} | {r['idf']} | {b} |")

    L += [
        "",
        "---",
        "",
        "## Observations",
        "",
        "### 1. Text-exclusive coinages dominate the top",
        "The highest-scoring terms are overwhelmingly **Rhys Davids coinages** —"
        " Victorian English vocabulary pressed into service for Pāli Abhidhamma concepts.",
        "Words like *self-collectedness*, *wieldiness*, *tractableness*, *pliancy* barely exist"
        " outside this translation, giving them near-maximum IDF.",
        "",
        "### 2. Buddhist technical register",
        "A tight cluster — *skandha*, *jhāna*, *āsava*, *supramundane*, *incorporeal* —"
        " forms the Buddhist technical register. These score extremely high because they belong"
        " to a specialist domain absent from general English, and they recur in every paragraph.",
        "",
        "### 3. The 'falsely familiar' vocabulary problem",
        "Rhys Davids consciously chose ordinary English words — *zest*, *ease*, *synergies*,"
        " *contact*, *feeling* — to avoid Pāli transliteration."
        " These occupy a mid-tier TF-IDF band: very frequent here, but their IDF is moderate"
        " because they do have a general English presence. They look everyday but carry"
        " specialist meaning.",
        "",
        "### 4. Repetition as structure inflates TF",
        "The *Dhammasaṅgaṇī* is formally repetitive by design (Buddhist catechism)."
        " Every mental factor is defined with the same formula across hundreds of consciousness"
        " types. Even moderately rare words (*volition*, *mindfulness*, *concomitant*)"
        " achieve unusually high raw frequencies relative to any other English text of"
        " equivalent length.",
        "",
        "---",
        "",
        f"*Corpus reference: Reuters-21578 (10,788 newswire documents) via NLTK · "
        f"sklearn TfidfVectorizer(smooth\\_idf=True, lowercase=True).*  ",
        f"*Generated {today} by `generate_termbase.py`.*",
    ]

    return "\n".join(L)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    if not EN_SOURCE.exists():
        raise FileNotFoundError(f"Translation not found:\n  {EN_SOURCE}")

    print(f"Reading  {EN_SOURCE.name} …")
    tf = count_tf(EN_SOURCE)
    print(f"  {len(tf):,} unique content tokens")

    rows = build_rows(tf)
    print(f"  {len(rows):,} terms scored")

    md = render_md(rows)
    OUTPUT.write_text(md, encoding="utf-8")

    word_count = len(md.split())
    print(f"  output word count ≈ {word_count:,}")
    print(f"Written  → {OUTPUT}")


if __name__ == "__main__":
    main()
